### ISSUE TITLE
Are there some errors in MAD?

### ISSUE THREAD

**Issue by kaiusgs** [I-Hope-Peace/ChangeDetectionRepository#3]
In irmad.py, line 51:
`eigenvector_Y = np.dot(np.dot(inv(sigma_22), sigma_21), eigenvector_X)  # the eigenvector of image Y`
I suppose the eigenvector of image Y should be divided by the eigenvalue, according to equations in the common way of solving CCA. 
`eigenvector_Y_ =np.dot(np.dot(inv(sigma_22), sigma_21), eigenvector_X) /eigenvalue`
Am I wrong or it's an error in code ?
Hope for your reply, and I'll be very thankful.

**Comment by ChenHongruixuan** [comment]
Sorry for my late reply. The data used for MAD should be centralized, so
the code uses the center_X and center_Y rather than X and Y. And
accordion to the formula of CCA, I don't think the eigenvector_Y should be
divided with eigenvalue. Because eigenvector_Y is solved according to its
relation with eigenvector_X, like the following:
[image: image.png]
[image: image.png]
You can refer to the original MATLAB implementation by Nilsen (
http://www.imm.dtu.dk/~alan/software.html).
